name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend_api:
    name: Backend (.NET 9)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore Tasky.sln

      - name: Build (Release)
        run: dotnet build Tasky.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Tasky.sln --configuration Release --no-build
        continue-on-error: true

      - name: Publish API
        run: dotnet publish src/Tasky.Api/Tasky.Api.csproj -c Release -o out/api

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: out/api

  frontend_web:
    name: Frontend (Vite + TS)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web/tasky-web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('web/tasky-web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/tasky-web/dist
